### ISSUE TITLE
linux

### ISSUE THREAD

**Issue by papycochon** [Quist0n/kitty_scripts#1]
use windiwnos

**Comment by JacqueSatan** [comment]
fuck yuu

**Comment by unixkeys** [comment]
fkuc  you

**Comment by JacqueSatan** [comment]
ETHYME

**Comment by Quist0n** [comment]
I have no idea as to why you are opening an issue complaining about something that is not an issue. I am going to simply close this and move on. If you have an actual problem or want to see a feature added, then you can open a new issue.

**Comment by papycochon** [comment]
linux is big isue
